In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Airline Quality Ratings.csv')

In [3]:
data[data.isnull().any(axis=1)]

ID  Gender  Age Customer Type Type of Travel         Class  \
246        247    Male   11     Returning       Business      Business   
883        884    Male   39     Returning       Business      Business   
1965      1966    Male   36     Returning       Business       Economy   
2407      2408  Female   55     Returning       Business      Business   
2448      2449    Male   21     Returning       Personal  Economy Plus   
...        ...     ...  ...           ...            ...           ...   
129000  129001    Male   46    First-time       Business      Business   
129003  129004  Female   17    First-time       Business       Economy   
129014  129015    Male   57     Returning       Business      Business   
129015  129016  Female   22     Returning       Business      Business   
129488  129489    Male   23     Returning       Personal       Economy   

        Flight Distance  Departure Delay  Arrival Delay  \
246                 719               38            NaN   
883                 396                0            NaN   
1965                383                2            NaN   
2407               2904               58            NaN   
2448                767                5            NaN   
...                 ...              ...            ...   
129000             2704                7            NaN   
129003             2704                0            NaN   
129014             2704                0            NaN   
129015             2611                8            NaN   
129488             2704                0            NaN   

        Departure and Arrival Time Convenience  ...  On-board Service  \
246                                          1  ...                 4   
883                                          3  ...                 3   
1965                                         4  ...                 5   
2407                                         5  ...                 4   
2448                                         3  ...                 4   
...                                        ...  ...               ...   
129000                                       3  ...                 4   
129003                                       3  ...                 2   
129014                                       4  ...                 4   
129015                                       3  ...                 4   
129488                                       1  ...                 1   

        Seat Comfort  Leg Room Service  Cleanliness  Food and Drink  \
246                4                 3            4               4   
883                4                 3            3               3   
1965               2                 2            2               2   
2407               3                 4            4               5   
2448               1                 2            1               1   
...              ...               ...          ...             ...   
129000             4                 2            4               4   
129003             1                 4            1               1   
129014             4                 4            5               2   
129015             4                 3            4               4   
129488             2                 3            2               2   

        In-flight Service  In-flight Wifi Service  In-flight Entertainment  \
246                     3                       4                        4   
883                     3                       3                        3   
1965                    2                       2                        2   
2407                    4                       4                        4   
2448                    2                       1                        1   
...                   ...                     ...                      ...   
129000                  4                       3                        4   
129003                  3                       3           

In [4]:
data[data.isnull().any(axis=1)].Age

246       11
883       39
1965      36
2407      55
2448      21
          ..
129000    46
129003    17
129014    57
129015    22
129488    23
Name: Age, Length: 393, dtype: int64

In [5]:
data = data.dropna()

In [6]:
yeni_data = data.fillna(int(data.Age.mean()))

In [7]:
data.Age.isnull()

0         False
1         False
2         False
3         False
4         False
          ...  
129875    False
129876    False
129877    False
129878    False
129879    False
Name: Age, Length: 129487, dtype: bool

In [8]:
data.notnull()

ID  Gender   Age  Customer Type  Type of Travel  Class  \
0       True    True  True           True            True   True   
1       True    True  True           True            True   True   
2       True    True  True           True            True   True   
3       True    True  True           True            True   True   
4       True    True  True           True            True   True   
...      ...     ...   ...            ...             ...    ...   
129875  True    True  True           True            True   True   
129876  True    True  True           True            True   True   
129877  True    True  True           True            True   True   
129878  True    True  True           True            True   True   
129879  True    True  True           True            True   True   

        Flight Distance  Departure Delay  Arrival Delay  \
0                  True             True           True   
1                  True             True           True   
2                  True             True           True   
3                  True             True           True   
4                  True             True           True   
...                 ...              ...            ...   
129875             True             True           True   
129876             True             True           True   
129877             True             True           True   
129878             True             True           True   
129879             True             True           True   

        Departure and Arrival Time Convenience  ...  On-board Service  \
0                                         True  ...              True   
1                                         True  ...              True   
2                                         True  ...              True   
3                                         True  ...              True   
4                                         True  ...              True   
...                                        ...  ...               ...   
129875                                    True  ...              True   
129876                                    True  ...              True   
129877                                    True  ...              True   
129878                                    True  ...              True   
129879                                    True  ...              True   

        Seat Comfort  Leg Room Service  Cleanliness  Food and Drink  \
0               True              True         True            True   
1               True              True         True            True   
2               True              True         True            True   
3               True              True         True            True   
4               True              True         True            True   
...              ...               ...          ...             ...   
129875          True              True         True            True   
129876          True              True         True            True   
129877          True              True         True            True   
129878          True              True         True            True   
129879          True              True         True            True   

        In-flight Service  In-flight Wifi Service  In-flight Entertainment  \
0                    True                    True                     True   
1                    True                    True                     True   
2                    True                    True                     True   
3                    True                    True                     True   
4                    True                    True                     True   
...                   ...                     ...                      ...   
129875               True                    True                     True   
129876               True                    True                     True   
129877               True                    True   

In [9]:
len(data[data.Age.isnull()==True])

0

In [10]:
len(data[data.Age.isnull()==False])

129487

In [11]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.1
[notice] To update, run: C:\Users\MONSTER\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [12]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import mean_absolute_error
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.neural_network import MLPClassifier


In [13]:
data.Gender.unique()

array(['Male', 'Female'], dtype=object)

In [14]:
genders = []
for i,row in data.iterrows():
    if row.Gender == "Female":
        genders.append(0)
    else:
        genders.append(1)

In [15]:
ages = data.Age.values

In [16]:
Departures = data["Departure Delay"].values

In [17]:
Arrivals = data["Arrival Delay"].values

In [18]:
data["Customer Type"].unique()

array(['First-time', 'Returning'], dtype=object)

In [19]:
customers = []
for i,row in data.iterrows():
    if row["Customer Type"] =="Returning": 
        customers.append(0)
    elif row["Customer Type"] =="First-time":
        customers.append(1)
    else:
        customers.append(2)

In [20]:
len(customers)

129487

In [21]:
Types = []
for i,row in data.iterrows():
    if row["Type of Travel"] =="Business":
        Types.append(0)
    elif row["Type of Travel"] =="Personal":
        Types.append(1)
    else:
        Types.append(2)

In [22]:
len(Types)

129487

In [23]:
import numpy as np

In [24]:
genders = np.array(genders)
ages = np.array(ages)
Departures = np.array(Departures)
Arrivals = np.array(Arrivals)
customers = np.array(customers)
egitim = np.stack((ages,genders,customers,),axis=1)
test = np.array(Types)

In [25]:
egitim

array([[48,  1,  1],
       [35,  0,  0],
       [41,  1,  0],
       ...,
       [42,  1,  0],
       [50,  1,  0],
       [20,  0,  0]], dtype=int64)

In [26]:
egitim.shape

(129487, 3)

In [27]:
test.shape

(129487,)

In [28]:
X_egitim, X_test, y_egitim, y_test = train_test_split(egitim,test,test_size=0.2,random_state=42) 

In [29]:
X_egitim.shape

(103589, 3)

In [30]:
siniflandirici = DecisionTreeClassifier()
siniflandirici.fit(X_egitim, y_egitim)

DecisionTreeClassifier()

In [31]:
tahminler = siniflandirici.predict(X_test)

In [32]:
tahminler

array([0, 0, 0, ..., 1, 0, 0])

In [33]:
y_test

array([0, 0, 1, ..., 1, 0, 1])

In [34]:
dogruluk = accuracy_score(y_test, tahminler)
dogruluk

0.7729940535948722