In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('onlinefoods.csv')

In [3]:
data.head(10)

Age  Gender Marital Status Occupation   Monthly Income  \
0   20  Female         Single    Student        No Income   
1   24  Female         Single    Student   Below Rs.10000   
2   22    Male         Single    Student   Below Rs.10000   
3   22  Female         Single    Student        No Income   
4   22    Male         Single    Student   Below Rs.10000   
5   27  Female        Married   Employee  More than 50000   
6   22    Male         Single    Student        No Income   
7   24  Female         Single    Student        No Income   
8   23  Female         Single    Student        No Income   
9   23  Female         Single    Student        No Income   

  Educational Qualifications  Family size  latitude  longitude  Pin code  \
0              Post Graduate            4   12.9766    77.5993    560001   
1                   Graduate            3   12.9770    77.5773    560009   
2              Post Graduate            3   12.9551    77.6593    560017   
3                   Graduate            6   12.9473    77.5616    560019   
4              Post Graduate            4   12.9850    77.5533    560010   
5              Post Graduate            2   12.9299    77.6848    560103   
6                   Graduate            3   12.9770    77.5773    560009   
7              Post Graduate            3   12.9828    77.6131    560042   
8              Post Graduate            2   12.9766    77.5993    560001   
9              Post Graduate            4   12.9854    77.7081    560048   

  Output   Feedback Unnamed: 12  
0    Yes   Positive         Yes  
1    Yes   Positive         Yes  
2    Yes  Negative          Yes  
3    Yes   Positive         Yes  
4    Yes   Positive         Yes  
5    Yes   Positive         Yes  
6    Yes   Positive         Yes  
7    Yes   Positive         Yes  
8    Yes   Positive         Yes  
9    Yes   Positive         Yes

In [4]:
data.describe()

Age  Family size    latitude   longitude       Pin code
count  388.000000   388.000000  388.000000  388.000000     388.000000
mean    24.628866     3.280928   12.972058   77.600160  560040.113402
std      2.975593     1.351025    0.044489    0.051354      31.399609
min     18.000000     1.000000   12.865200   77.484200  560001.000000
25%     23.000000     2.000000   12.936900   77.565275  560010.750000
50%     24.000000     3.000000   12.977000   77.592100  560033.500000
75%     26.000000     4.000000   12.997025   77.630900  560068.000000
max     33.000000     6.000000   13.102000   77.758200  560109.000000

In [5]:
data[data.isnull().any(axis=1)]

Empty DataFrame
Columns: [Age, Gender, Marital Status, Occupation, Monthly Income, Educational Qualifications, Family size, latitude, longitude, Pin code, Output, Feedback, Unnamed: 12]
Index: []

In [6]:
data[data.isnull().any(axis=1)].Age

Series([], Name: Age, dtype: int64)

In [7]:
data.iloc[0,0] = int(data.Age.mean())

In [8]:
data.head()

Age  Gender Marital Status Occupation  Monthly Income  \
0   24  Female         Single    Student       No Income   
1   24  Female         Single    Student  Below Rs.10000   
2   22    Male         Single    Student  Below Rs.10000   
3   22  Female         Single    Student       No Income   
4   22    Male         Single    Student  Below Rs.10000   

  Educational Qualifications  Family size  latitude  longitude  Pin code  \
0              Post Graduate            4   12.9766    77.5993    560001   
1                   Graduate            3   12.9770    77.5773    560009   
2              Post Graduate            3   12.9551    77.6593    560017   
3                   Graduate            6   12.9473    77.5616    560019   
4              Post Graduate            4   12.9850    77.5533    560010   

  Output   Feedback Unnamed: 12  
0    Yes   Positive         Yes  
1    Yes   Positive         Yes  
2    Yes  Negative          Yes  
3    Yes   Positive         Yes  
4    Yes   Positive         Yes

In [9]:
data = data.dropna()

In [10]:
data.head()

Age  Gender Marital Status Occupation  Monthly Income  \
0   24  Female         Single    Student       No Income   
1   24  Female         Single    Student  Below Rs.10000   
2   22    Male         Single    Student  Below Rs.10000   
3   22  Female         Single    Student       No Income   
4   22    Male         Single    Student  Below Rs.10000   

  Educational Qualifications  Family size  latitude  longitude  Pin code  \
0              Post Graduate            4   12.9766    77.5993    560001   
1                   Graduate            3   12.9770    77.5773    560009   
2              Post Graduate            3   12.9551    77.6593    560017   
3                   Graduate            6   12.9473    77.5616    560019   
4              Post Graduate            4   12.9850    77.5533    560010   

  Output   Feedback Unnamed: 12  
0    Yes   Positive         Yes  
1    Yes   Positive         Yes  
2    Yes  Negative          Yes  
3    Yes   Positive         Yes  
4    Yes   Positive         Yes

In [11]:
yeni_data = data.fillna(int(data.Age.mean()))

In [12]:
yeni_data.head(10)

Age  Gender Marital Status Occupation   Monthly Income  \
0   24  Female         Single    Student        No Income   
1   24  Female         Single    Student   Below Rs.10000   
2   22    Male         Single    Student   Below Rs.10000   
3   22  Female         Single    Student        No Income   
4   22    Male         Single    Student   Below Rs.10000   
5   27  Female        Married   Employee  More than 50000   
6   22    Male         Single    Student        No Income   
7   24  Female         Single    Student        No Income   
8   23  Female         Single    Student        No Income   
9   23  Female         Single    Student        No Income   

  Educational Qualifications  Family size  latitude  longitude  Pin code  \
0              Post Graduate            4   12.9766    77.5993    560001   
1                   Graduate            3   12.9770    77.5773    560009   
2              Post Graduate            3   12.9551    77.6593    560017   
3                   Graduate            6   12.9473    77.5616    560019   
4              Post Graduate            4   12.9850    77.5533    560010   
5              Post Graduate            2   12.9299    77.6848    560103   
6                   Graduate            3   12.9770    77.5773    560009   
7              Post Graduate            3   12.9828    77.6131    560042   
8              Post Graduate            2   12.9766    77.5993    560001   
9              Post Graduate            4   12.9854    77.7081    560048   

  Output   Feedback Unnamed: 12  
0    Yes   Positive         Yes  
1    Yes   Positive         Yes  
2    Yes  Negative          Yes  
3    Yes   Positive         Yes  
4    Yes   Positive         Yes  
5    Yes   Positive         Yes  
6    Yes   Positive         Yes  
7    Yes   Positive         Yes  
8    Yes   Positive         Yes  
9    Yes   Positive         Yes

In [13]:
data[data.isnull().any(axis=1)].Age

Series([], Name: Age, dtype: int64)

In [14]:
data.Age.isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
383    False
384    False
385    False
386    False
387    False
Name: Age, Length: 388, dtype: bool

In [15]:
data.notnull()

Age  Gender  Marital Status  Occupation  Monthly Income  \
0    True    True            True        True            True   
1    True    True            True        True            True   
2    True    True            True        True            True   
3    True    True            True        True            True   
4    True    True            True        True            True   
..    ...     ...             ...         ...             ...   
383  True    True            True        True            True   
384  True    True            True        True            True   
385  True    True            True        True            True   
386  True    True            True        True            True   
387  True    True            True        True            True   

     Educational Qualifications  Family size  latitude  longitude  Pin code  \
0                          True         True      True       True      True   
1                          True         True      True       True      True   
2                          True         True      True       True      True   
3                          True         True      True       True      True   
4                          True         True      True       True      True   
..                          ...          ...       ...        ...       ...   
383                        True         True      True       True      True   
384                        True         True      True       True      True   
385                        True         True      True       True      True   
386                        True         True      True       True      True   
387                        True         True      True       True      True   

     Output  Feedback  Unnamed: 12  
0      True      True         True  
1      True      True         True  
2      True      True         True  
3      True      True         True  
4      True      True         True  
..      ...       ...          ...  
383    True      True         True  
384    True      True         True  
385    True      True         True  
386    True      True         True  
387    True      True         True  

[388 rows x 13 columns]

In [16]:
len(data[data.Age.isnull()==True])

0

In [17]:
len(data[data.Age.isnull()==False])

388

In [18]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [19]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [20]:
data.Gender.unique()

array(['Female', 'Male'], dtype=object)

In [21]:
genders = []
for i,row in data.iterrows():
    if row.Gender == "Female":
        genders.append(0)
    else:
        genders.append(1)

In [22]:
ages = data.Age.values

In [23]:
data["Marital Status"].unique()

array(['Single', 'Married', 'Prefer not to say'], dtype=object)

In [24]:
maritals = []
for i,row in data.iterrows():
    if row["Marital Status"] =="Single":
        maritals.append(0)
    elif row["Marital Status"] =="Married":
        maritals.append(1)
    else:
        maritals.append(2)

In [25]:
len(maritals)

388

In [26]:
data.Occupation.unique()

array(['Student', 'Employee', 'Self Employeed', 'House wife'],
      dtype=object)

In [27]:
occupations = []
for i,row in data.iterrows():
    if row.Occupation == "Student":
        occupations.append(0)
    elif row.Occupation == "Employee":
        occupations.append(1)
    elif row.Occupation == "Self Employeed":
        occupations.append(2)
    else:
        occupations.append(3)

In [28]:
import numpy as np

In [29]:
genders = np.array(genders)
ages = np.array(ages)
maritals = np.array(maritals)
egitim = np.stack((ages,genders,maritals),axis=1)
test = np.array(occupations)

In [30]:
egitim

array([[24,  0],
       [24,  0],
       [22,  1],
       [22,  0],
       [22,  1],
       [27,  0],
       [22,  1],
       [24,  0],
       [23,  0],
       [23,  0],
       [22,  0],
       [23,  1],
       [23,  1],
       [21,  1],
       [23,  0],
       [24,  0],
       [28,  0],
       [23,  0],
       [25,  1],
       [21,  0],
       [24,  1],
       [22,  1],
       [22,  0],
       [23,  1],
       [21,  1],
       [25,  1],
       [22,  0],
       [22,  1],
       [23,  0],
       [22,  1],
       [22,  0],
       [22,  1],
       [25,  1],
       [22,  0],
       [22,  0],
       [25,  1],
       [25,  1],
       [32,  0],
       [23,  0],
       [23,  0],
       [30,  1],
       [23,  1],
       [23,  1],
       [22,  0],
       [22,  1],
       [27,  0],
       [24,  0],
       [23,  1],
       [23,  0],
       [22,  0],
       [23,  0],
       [23,  0],
       [24,  1],
       [25,  1],
       [22,  1],
       [28,  0],
       [22,  0],
       [24,  0],
       [31,  1

In [31]:
egitim.shape

(388, 2)

In [32]:
test.shape

(388,)

In [33]:
X_egitim, X_test, y_egitim, y_test = train_test_split(egitim,test,test_size=0.2,random_state=42) 

In [34]:
X_egitim.shape

(310, 2)

In [35]:
siniflandirici = DecisionTreeClassifier()
siniflandirici.fit(X_egitim, y_egitim)

DecisionTreeClassifier()

In [36]:
tahminler = siniflandirici.predict(X_test)

In [37]:
tahminler

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 2, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 2,
       2, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [38]:
y_test

array([1, 0, 0, 0, 1, 0, 0, 0, 3, 1, 2, 1, 1, 0, 3, 1, 0, 3, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 0, 1,
       2, 1, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2])

In [39]:
dogruluk = accuracy_score(y_test, tahminler)
dogruluk

0.7307692307692307